name: mne_realtime
channels:
- defaults
dependencies:
- python
- pip
- numpy
- scipy
- matplotlib
- pyqt
- scikit-learn
- pillow
- pytest
- pytest-cov
- flaky
- numpydoc
- flake8
- liblsl
- mne
- pydocstyle
- pip:
  - pylsl
